// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { assign } from "./assign.js";
import { clone } from "./clone.js";
import { entries } from "./entries.js";
import { evolve } from "./evolve.js";
import { forEach } from "./forEach.js";
import { fromEntries } from "./fromEntries.js";
import { get } from "./get.js";
import { getOr } from "./getOr.js";
import { getOrElse } from "./getOrElse.js";
import { getOrThrow } from "./getOrThrow.js";
import { hasKey } from "./hasKey.js";
import { hasProp } from "./hasProp.js";
import { is } from "./is.js";
import { isEmpty } from "./isEmpty.js";
import { isShallowEqual } from "./isShallowEqual.js";
import { keys } from "./keys.js";
import { map } from "./map.js";
import { mapAssign } from "./mapAssign.js";
import { mapMerge } from "./mapMerge.js";
import { matches } from "./matches.js";
import { merge } from "./merge.js";
import { omit } from "./omit.js";
import { pick } from "./pick.js";
import { propIs } from "./propIs.js";
import { set } from "./set.js";
import { test } from "./test.js";
import { testAll } from "./testAll.js";
import { values } from "./values.js";

export const Object = {
    assign,
    clone,
    entries,
    evolve,
    forEach,
    fromEntries,
    get,
    getOr,
    getOrElse,
    getOrThrow,
    hasKey,
    hasProp,
    is,
    isEmpty,
    isShallowEqual,
    keys,
    map,
    mapAssign,
    mapMerge,
    matches,
    merge,
    omit,
    pick,
    propIs,
    set,
    test,
    testAll,
    values,
}
